spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jingkai?useUnicode=true&characterEncoding=utf-8
    username: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis: 
   mapperLocations: classpath:mybatis/*.xml